endpoints:

  # - name: local-health
  #   group: internal
  #   url: "http://localhost:8080/health"
  #   interval: 30s
  #   conditions:
  #     - "[STATUS] == 200"
  #     - "[BODY].status == ok"
  #     - "[RESPONSE_TIME] < 200"

  - name: service-health
    group: core
    url: "https://aliabukar.com/health"
    interval: 1m
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 1000"

  - name: front-end
    group: core
    url: "https://twin.sh/health"
    interval: 5m
    conditions:
      - "[STATUS] == 200"
      - "[BODY].status == UP"

  - name: back-end
    group: core
    url: "https://example.org/"
    interval: 5m
    conditions:
      - "[STATUS] == 200"
      - "[CERTIFICATE_EXPIRATION] > 48h"

  - name: monitoring
    group: internal
    url: "https://example.org/"
    interval: 5m
    conditions:
      - "[STATUS] == 200"

  - name: nas
    group: internal
    url: "https://example.org/"
    interval: 5m
    conditions:
      - "[STATUS] == 200"

  - name: aliabukar-main
    url: https://aliabukar.com
    interval: 1m
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 500"

  - name: domain-tls
    url: https://aliabukar.com
    interval: 1m
    conditions:
      - "[CONNECTED] == true"

  - name: icmp-ping
    url: "icmp://google.com"
    interval: 1m
    conditions:
      - "[CONNECTED] == true"

  - name: check-domain-expiration
    url: "https://aliabukar.com/"
    interval: 1h
    conditions:
      - "[DOMAIN_EXPIRATION] > 720h"


  - name: dns-query
    url: "8.8.8.8"
    interval: 5m
    dns:
      query-name: "google.com"
      query-type: "A"
    conditions:
      # - "[BODY] == pat(*.*.*.*)"  # Matches any IPv4 address
      - "[DNS_RCODE] == NOERROR"
