name: Build, Test and Push to ECR

on: [push]


permissions:

  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2


    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume:  ${{ secrets.AWS_OIDC_ROLE }}
        aws-region: eu-west-2

    # Login to ECR
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    # Set environment variables for unique Docker image name
    - name: Set image variables
      env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: my-ecr-repo
          IMAGE_TAG: ${{ github.sha }}
          run: echo "Variables are set

    - name: Debug variables
      run: |
          echo "REGISTRY=[$REGISTRY]"
          echo "REPOSITORY=[$REPOSITORY]"
          echo "IMAGE_TAG=[$IMAGE_TAG]"
      env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: my-ecr-repo
          IMAGE_TAG: ${{ github.sha }}

    # Build and Tag Container Image
    - name: Build container image
      run: |
        echo "Building image ${REGISTRY}/${REPOSITORY}:${IMAGE_TAG}"
        docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG -t $REGISTRY/$REPOSITORY:memos .
    # Test the image
    - name: Test container
      run: |
        docker run --rm $REGISTRY/$REPOSITORY:$IMAGE_TAG echo "mem memo memos"
   
    
    - name: Push docker image to Amazon ECR
      run: |
        docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
        docker push $REGISTRY/$REPOSITORY:memos






