name: Terraform Init, Plan and Apply
on:
  push:
    # paths:
    #   - '/terraform/**'
    #   - '.github/workflows/tf*.yaml'

permissions:
  id-token: write
  contents: read
  pull-requests: write


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume:  ${{ secrets.AWS_OIDC_ROLE }}
        aws-region: eu-west-2

    - name: Terraform validate
      uses: dflook/terraform-validate@v2
      id: validate
      with:
          path: terraform

    - name: Setup TFLint
      uses: terraform-linters/setup-tflint@v6
      with:
        tflint_version: v0.52.0
        cache: true
    
    - name: terraform fmt
      uses: dflook/terraform-fmt@v2
      with:
          path: terraform

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
          commit-message: terraform fmt
          title: Reformat terraform files
          body: Update Terraform files to canonical format using `terraform fmt`
          branch: automated-terraform-fmt
      continue-on-error: true


    # - name: Terraform security scan (tfsec)
    #   uses: triat/terraform-security-scan@v3.0.0
    #   with:
    #     path: terraform          
    #     scanners: tfsec    
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   continue-on-error: true


    - name: terraform plan
      uses: dflook/terraform-plan@v2
      with:
          path: terraform
    
    - name: terraform apply
      env:
          TF_VAR_GODADDY_API_KEY: ${{ secrets.GODADDY_API_KEY }}
          TF_VAR_GODADDY_API_SECRET: ${{ secrets.GODADDY_API_SECRET }}
      uses: dflook/terraform-apply@v2.2.3
      with:
        path: terraform
        auto-approve: true